# Generated by Django 3.2.5 on 2022-09-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comment',
            new_name='products',
        ),
    ]
