# Generated by Django 4.1.1 on 2022-09-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_order_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
